"""Initial migration

Revision ID: 7924ca284413
Revises: 
Create Date: 2025-03-04 00:05:47.819548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7924ca284413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('Type_id', sa.Integer(), nullable=False),
    sa.Column('Type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Type_id')
    )
    op.create_table('user',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=500), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('First_name', sa.String(length=50), nullable=False),
    sa.Column('Middle_name', sa.String(length=50), nullable=True),
    sa.Column('Surname', sa.String(length=50), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=False),
    sa.Column('Level_of_access', sa.Integer(), nullable=False),
    sa.Column('Is_expert', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('User_id')
    )
    op.create_table('address',
    sa.Column('Address_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Line_1', sa.String(length=50), nullable=False),
    sa.Column('Line_2', sa.String(length=50), nullable=False),
    sa.Column('Country', sa.String(length=50), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=False),
    sa.Column('Region', sa.String(length=50), nullable=False),
    sa.Column('Postcode', sa.String(length=50), nullable=False),
    sa.Column('Is_billing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Address_id')
    )
    op.create_table('items',
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Listing_name', sa.String(length=50), nullable=False),
    sa.Column('Seller_id', sa.Integer(), nullable=False),
    sa.Column('Expert_id', sa.Integer(), nullable=True),
    sa.Column('Verified', sa.Boolean(), nullable=False),
    sa.Column('Upload_datetime', sa.DateTime(), nullable=True),
    sa.Column('Available_until', sa.DateTime(), nullable=False),
    sa.Column('Min_price', sa.Float(), nullable=False),
    sa.Column('Current_bid', sa.Float(), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.Column('Authentication_request', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Expert_id'], ['user.User_id'], ),
    sa.ForeignKeyConstraint(['Seller_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Item_id')
    )
    op.create_table('payment',
    sa.Column('Payment_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Card_Number', sa.Integer(), nullable=False),
    sa.Column('CVV', sa.Integer(), nullable=False),
    sa.Column('Expiry', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Payment_id')
    )
    op.create_table('bidding_history',
    sa.Column('Bid_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Bidder_id', sa.Integer(), nullable=False),
    sa.Column('Successful_bid', sa.Boolean(), nullable=False),
    sa.Column('Bid_datetime', sa.DateTime(), nullable=True),
    sa.Column('Bid_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Bidder_id'], ['user.User_id'], ),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.PrimaryKeyConstraint('Bid_id')
    )
    op.create_table('images',
    sa.Column('Image_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Image', sa.LargeBinary(), nullable=False),
    sa.Column('Image_description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.PrimaryKeyConstraint('Image_id')
    )
    op.create_table('middle_type',
    sa.Column('Middle_type_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.ForeignKeyConstraint(['Type_id'], ['types.Type_id'], ),
    sa.PrimaryKeyConstraint('Middle_type_id')
    )
    op.create_table('watchlist',
    sa.Column('Watchlist_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Watchlist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('middle_type')
    op.drop_table('images')
    op.drop_table('bidding_history')
    op.drop_table('payment')
    op.drop_table('items')
    op.drop_table('address')
    op.drop_table('user')
    op.drop_table('types')
    # ### end Alembic commands ###
