"""Initial migration

Revision ID: f227c28457eb
Revises: 
Create Date: 2025-03-17 21:12:50.176095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f227c28457eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit_structure',
    sa.Column('Structure_id', sa.Integer(), nullable=False),
    sa.Column('Expert_split', sa.Float(), nullable=False),
    sa.Column('Manager_split', sa.Float(), nullable=False),
    sa.Column('Enforced_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Structure_id')
    )
    op.create_table('types',
    sa.Column('Type_id', sa.Integer(), nullable=False),
    sa.Column('Type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Type_id')
    )
    op.create_table('user',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=500), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('First_name', sa.String(length=50), nullable=False),
    sa.Column('Middle_name', sa.String(length=50), nullable=True),
    sa.Column('Surname', sa.String(length=50), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=False),
    sa.Column('Level_of_access', sa.Integer(), nullable=False),
    sa.Column('Is_expert', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('User_id')
    )
    op.create_table('address',
    sa.Column('Address_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Line_1', sa.String(length=50), nullable=False),
    sa.Column('Line_2', sa.String(length=50), nullable=False),
    sa.Column('Country', sa.String(length=50), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=False),
    sa.Column('Region', sa.String(length=50), nullable=False),
    sa.Column('Postcode', sa.String(length=50), nullable=False),
    sa.Column('Is_billing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Address_id')
    )
    op.create_table('availabilities',
    sa.Column('Availability_id', sa.Integer(), nullable=False),
    sa.Column('Expert_id', sa.Integer(), nullable=False),
    sa.Column('Day_of_week', sa.Integer(), nullable=False),
    sa.Column('Start_time', sa.Time(), nullable=False),
    sa.Column('End_time', sa.Time(), nullable=False),
    sa.Column('Week_start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['Expert_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Availability_id')
    )
    op.create_table('items',
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Listing_name', sa.String(length=50), nullable=False),
    sa.Column('Seller_id', sa.Integer(), nullable=False),
    sa.Column('Upload_datetime', sa.DateTime(), nullable=True),
    sa.Column('Available_until', sa.DateTime(), nullable=False),
    sa.Column('Min_price', sa.Float(), nullable=False),
    sa.Column('Current_bid', sa.Float(), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.Column('Structure_id', sa.Integer(), nullable=True),
    sa.Column('Expert_id', sa.Integer(), nullable=True),
    sa.Column('Verified', sa.Boolean(), nullable=False),
    sa.Column('Authentication_request', sa.Boolean(), nullable=False),
    sa.Column('Authentication_request_approved', sa.Boolean(), nullable=True),
    sa.Column('Second_opinion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Expert_id'], ['user.User_id'], ),
    sa.ForeignKeyConstraint(['Seller_id'], ['user.User_id'], ),
    sa.ForeignKeyConstraint(['Structure_id'], ['profit_structure.Structure_id'], ),
    sa.PrimaryKeyConstraint('Item_id')
    )
    op.create_table('middle_expertise',
    sa.Column('Middle_expertise_id', sa.Integer(), nullable=False),
    sa.Column('Expert_id', sa.Integer(), nullable=False),
    sa.Column('Type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Expert_id'], ['user.User_id'], ),
    sa.ForeignKeyConstraint(['Type_id'], ['types.Type_id'], ),
    sa.PrimaryKeyConstraint('Middle_expertise_id')
    )
    op.create_table('payment',
    sa.Column('Payment_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Card_Number', sa.Integer(), nullable=False),
    sa.Column('CVV', sa.Integer(), nullable=False),
    sa.Column('Expiry', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Payment_id')
    )
    op.create_table('bidding_history',
    sa.Column('Bid_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Bidder_id', sa.Integer(), nullable=False),
    sa.Column('Successful_bid', sa.Boolean(), nullable=False),
    sa.Column('Bid_datetime', sa.DateTime(), nullable=True),
    sa.Column('Bid_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Bidder_id'], ['user.User_id'], ),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.PrimaryKeyConstraint('Bid_id')
    )
    op.create_table('chat',
    sa.Column('Chat_id', sa.Integer(), nullable=False),
    sa.Column('Sender_id', sa.Integer(), nullable=False),
    sa.Column('Recipient_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.ForeignKeyConstraint(['Recipient_id'], ['user.User_id'], ),
    sa.ForeignKeyConstraint(['Sender_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Chat_id')
    )
    op.create_table('images',
    sa.Column('Image_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Image', sa.LargeBinary(), nullable=False),
    sa.Column('Image_description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.PrimaryKeyConstraint('Image_id')
    )
    op.create_table('middle_type',
    sa.Column('Middle_type_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.Column('Type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.ForeignKeyConstraint(['Type_id'], ['types.Type_id'], ),
    sa.PrimaryKeyConstraint('Middle_type_id')
    )
    op.create_table('watchlist',
    sa.Column('Watchlist_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Item_id'], ['items.Item_id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Watchlist_id')
    )
    op.create_table('chat_messages',
    sa.Column('Message_id', sa.Integer(), nullable=False),
    sa.Column('Chat_id', sa.Integer(), nullable=False),
    sa.Column('Sender_id', sa.Integer(), nullable=False),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('Image', sa.LargeBinary(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('Read', sa.Boolean(), nullable=False),
    sa.Column('Read_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Chat_id'], ['chat.Chat_id'], ),
    sa.ForeignKeyConstraint(['Sender_id'], ['user.User_id'], ),
    sa.PrimaryKeyConstraint('Message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('watchlist')
    op.drop_table('middle_type')
    op.drop_table('images')
    op.drop_table('chat')
    op.drop_table('bidding_history')
    op.drop_table('payment')
    op.drop_table('middle_expertise')
    op.drop_table('items')
    op.drop_table('availabilities')
    op.drop_table('address')
    op.drop_table('user')
    op.drop_table('types')
    op.drop_table('profit_structure')
    # ### end Alembic commands ###
